# Generated by Django 4.1.5 on 2023-04-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gameflix_app', '0002_alter_video_author_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/profile_images/default.jpg', upload_to='profile_images/'),
        ),
    ]
